### ISSUE TITLE
Wrong SHA256 checksum in vm-linux-ubuntuserver-amd64-18.04.conf

### ISSUE THREAD

**Issue by barthel** [cbsd/cbsd-vmprofiles#3]
The SHA256 checksum file at http://ftp.halifax.rwth-aachen.de/ubuntu-releases/18.04.1/SHA256SUMS contains the SHA256 checksum:
```
7b37dfcd082726303528e47c82f88f29c1dc9232f8fd39120d13749ae83cc463 *ubuntu-18.04.1.0-live-server-amd64.iso
```
but in ```vm-linux-ubuntuserver-amd64-18.04.conf``` the SHA256 checksum is different:
```
sha256sum="a825805899310626474ec22340bf42b69ccb222aeb0ff1ed481793fa3e81cbfb"
```

**Comment by olevole** [comment]
Thx! unfortunately we do not control changes on master sites, for this reason CBSD vm profiles submitted to public/external resource for contributing. 

You can use 'Update from GIT' button on bconstruct-tui -> vm_os_profile to fetch updates
